
import __ASTRO_IMAGE_IMPORT_gVLM6 from "../../assets/projects/almaissues/hero.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Falmaissues.mdx";
import __ASTRO_IMAGE_IMPORT_UwgLB from "../../assets/projects/almaissues/products.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Falmaissues.mdx";
import __ASTRO_IMAGE_IMPORT_Z8yw3h from "../../assets/projects/gocha/browser.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Fgocha.mdx";
import __ASTRO_IMAGE_IMPORT_1Md4YO from "../../assets/projects/illume/hero.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Fillume.mdx";
import __ASTRO_IMAGE_IMPORT_1Y7GhK from "../../assets/projects/illume/events.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Fillume.mdx";
import __ASTRO_IMAGE_IMPORT_F11JH from "../../assets/projects/imentor/mockup.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2FiMentor.mdx";
import __ASTRO_IMAGE_IMPORT_Z2audzt from "../../assets/projects/mrstick/mr_stick.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Fmr-stick.mdx";
import __ASTRO_IMAGE_IMPORT_ZeqXxT from "../../assets/projects/hollywood/BI-insights.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fhollywood-movies.mdx";
import __ASTRO_IMAGE_IMPORT_ZP5ACD from "../../assets/projects/hollywood/R-trends.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fhollywood-movies.mdx";
import __ASTRO_IMAGE_IMPORT_ZJKeBG from "../../assets/projects/la_crime/la-dashboard.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fla-crime.mdx";
import __ASTRO_IMAGE_IMPORT_29rxuY from "../../assets/projects/yapic/home.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Fyapic.mdx";
import __ASTRO_IMAGE_IMPORT_Z21TjC8 from "../../assets/projects/yapic/yapic_log.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Fyapic.mdx";
import __ASTRO_IMAGE_IMPORT_19mMPL from "../../assets/projects/superstore/kpi.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fsuperstore.mdx";
import __ASTRO_IMAGE_IMPORT_1QEhqB from "../../assets/projects/superstore/returns.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fsuperstore.mdx";
import __ASTRO_IMAGE_IMPORT_UIeEa from "../../assets/projects/wealth_nations/dashboard.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fwealth-nations.mdx";
import __ASTRO_IMAGE_IMPORT_e2i1M from "../../assets/projects/wealth_nations/excel.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fwealth-nations.mdx";
import __ASTRO_IMAGE_IMPORT_Z2eCSu2 from "../../assets/projects/world/eda.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fworld.mdx";
import __ASTRO_IMAGE_IMPORT_2lc1a6 from "../../assets/projects/world/sql_explore.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fworld.mdx";
export default new Map([["../../assets/projects/almaissues/hero.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Falmaissues.mdx", __ASTRO_IMAGE_IMPORT_gVLM6], ["../../assets/projects/almaissues/products.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Falmaissues.mdx", __ASTRO_IMAGE_IMPORT_UwgLB], ["../../assets/projects/gocha/browser.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Fgocha.mdx", __ASTRO_IMAGE_IMPORT_Z8yw3h], ["../../assets/projects/illume/hero.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Fillume.mdx", __ASTRO_IMAGE_IMPORT_1Md4YO], ["../../assets/projects/illume/events.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Fillume.mdx", __ASTRO_IMAGE_IMPORT_1Y7GhK], ["../../assets/projects/imentor/mockup.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2FiMentor.mdx", __ASTRO_IMAGE_IMPORT_F11JH], ["../../assets/projects/mrstick/mr_stick.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Fmr-stick.mdx", __ASTRO_IMAGE_IMPORT_Z2audzt], ["../../assets/projects/hollywood/BI-insights.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fhollywood-movies.mdx", __ASTRO_IMAGE_IMPORT_ZeqXxT], ["../../assets/projects/hollywood/R-trends.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fhollywood-movies.mdx", __ASTRO_IMAGE_IMPORT_ZP5ACD], ["../../assets/projects/la_crime/la-dashboard.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fla-crime.mdx", __ASTRO_IMAGE_IMPORT_ZJKeBG], ["../../assets/projects/yapic/home.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Fyapic.mdx", __ASTRO_IMAGE_IMPORT_29rxuY], ["../../assets/projects/yapic/yapic_log.png?astroContentImageFlag=&importer=src%2Fdata%2Fweb-projects%2Fyapic.mdx", __ASTRO_IMAGE_IMPORT_Z21TjC8], ["../../assets/projects/superstore/kpi.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fsuperstore.mdx", __ASTRO_IMAGE_IMPORT_19mMPL], ["../../assets/projects/superstore/returns.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fsuperstore.mdx", __ASTRO_IMAGE_IMPORT_1QEhqB], ["../../assets/projects/wealth_nations/dashboard.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fwealth-nations.mdx", __ASTRO_IMAGE_IMPORT_UIeEa], ["../../assets/projects/wealth_nations/excel.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fwealth-nations.mdx", __ASTRO_IMAGE_IMPORT_e2i1M], ["../../assets/projects/world/eda.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fworld.mdx", __ASTRO_IMAGE_IMPORT_Z2eCSu2], ["../../assets/projects/world/sql_explore.png?astroContentImageFlag=&importer=src%2Fdata%2Fdata-projects%2Fworld.mdx", __ASTRO_IMAGE_IMPORT_2lc1a6]]);
		